import React, { useState, useEffect } from "react";
import { 
  Users, Wifi, Radio, QrCode, Eye, Sparkles, 
  TrendingUp, AlertTriangle, Play, HelpCircle, Server
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

interface SensorMetrics {
  cctvCount: number;
  wifiLogins: number;
  bluetoothPings: number;
  ticketScansMin: number;
  iotFloorPlates: number;
}

export default function CrowdPredictor() {
  const [matchPhase, setMatchPhase] = useState<"ingress" | "halftime" | "egress">("ingress");
  
  // Base raw sensor feeds
  const [sensorData, setSensorData] = useState<SensorMetrics>({
    cctvCount: 3840,
    wifiLogins: 42800,
    bluetoothPings: 21400,
    ticketScansMin: 340,
    iotFloorPlates: 84
  });

  const [simulationActive, setSimulationActive] = useState<boolean>(true);
  
  // Predicted metrics generated by AI model
  const [bottleneckRisk, setBottleneckRisk] = useState<"Low" | "Medium" | "High" | "Critical">("High");
  const [criticalSectors, setCriticalSectors] = useState<string[]>([]);
  const [predictedGateWaitTimes, setPredictedGateWaitTimes] = useState<Record<string, number>>({
    "North Gate A": 8,
    "East Gate B": 24,
    "South Gate C": 38,
    "West Gate D": 12
  });

  // Periodically fluctuate sensor metrics when simulation is running
  useEffect(() => {
    if (!simulationActive) return;

    const interval = setInterval(() => {
      setSensorData((prev) => {
        let baseMultiplier = 1.0;
        if (matchPhase === "ingress") baseMultiplier = 1.2;
        if (matchPhase === "halftime") baseMultiplier = 1.4;
        if (matchPhase === "egress") baseMultiplier = 1.6;

        const fluctuate = (val: number, rangePct: number) => {
          const delta = (Math.random() * 2 - 1) * rangePct * val;
          return Math.round(val + delta);
        };

        return {
          cctvCount: Math.min(12000, Math.max(1200, fluctuate(3500 * baseMultiplier, 0.05))),
          wifiLogins: Math.min(85000, Math.max(10000, fluctuate(40000 * baseMultiplier, 0.02))),
          bluetoothPings: Math.min(45000, Math.max(5000, fluctuate(20000 * baseMultiplier, 0.04))),
          ticketScansMin: matchPhase === "halftime" ? 10 : Math.min(1200, Math.max(40, fluctuate(320 * (matchPhase === "ingress" ? 2.2 : 0.4), 0.08))),
          iotFloorPlates: Math.min(100, Math.max(10, fluctuate(75 * baseMultiplier, 0.06)))
        };
      });
    }, 3000);

    return () => clearInterval(interval);
  }, [simulationActive, matchPhase]);

  // Re-calculate predictions when sensor counts change
  useEffect(() => {
    let risk: "Low" | "Medium" | "High" | "Critical" = "Low";
    let sects: string[] = [];
    const totalActivityScore = (sensorData.cctvCount / 3000) + (sensorData.wifiLogins / 30000) + (sensorData.ticketScansMin / 200);

    if (totalActivityScore > 5.0) {
      risk = "Critical";
      sects = ["South Gate C Escalators", "Section 104 Bottleneck Corridor", "Metro Station Transit Tunnel"];
    } else if (totalActivityScore > 3.0) {
      risk = "High";
      sects = ["South Gate C Entrance Plaza", "East Stand Concession Queue B"];
    } else if (totalActivityScore > 1.5) {
      risk = "Medium";
      sects = ["North Gate A Main Ingress"];
    } else {
      risk = "Low";
      sects = ["No major bottlenecks forecast"];
    }

    setBottleneckRisk(risk);
    setCriticalSectors(sects);

    // Predict gate queues 15m/30m out
    setPredictedGateWaitTimes({
      "North Gate A": Math.max(3, Math.round(sensorData.cctvCount * 0.0015)),
      "East Gate B": Math.max(5, Math.round(sensorData.wifiLogins * 0.00045)),
      "South Gate C": Math.max(10, Math.round(sensorData.ticketScansMin * 0.12 + (sensorData.cctvCount * 0.006))),
      "West Gate D": Math.max(4, Math.round(sensorData.bluetoothPings * 0.00045))
    });

  }, [sensorData]);

  return (
    <div className="bg-zinc-950 border border-white/10 rounded-none p-6 sm:p-8" id="crowd-density-prediction-panel">
      
      {/* Title block */}
      <div className="flex flex-col md:flex-row md:items-baseline justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center space-x-2 text-blue-500 font-mono text-[10px] uppercase tracking-widest font-black mb-1.5">
            <Sparkles className="h-3.5 w-3.5 text-blue-400 animate-pulse" />
            <span>AI_PREDICTIVE_CROWD_TELEMETRY</span>
          </div>
          <h3 className="text-3xl font-black italic tracking-tighter uppercase text-white">
            AI CROWD PREDICTOR
          </h3>
          <p className="text-xs text-zinc-400 mt-1 max-w-lg leading-relaxed">
            Neural predictive model parsing CCTV vision streams, WiFi device handshakes, ticket scans, and IoT beacons to predict stadium overcrowding 15-60m out.
          </p>
        </div>

        {/* Play/Pause controls */}
        <button
          onClick={() => setSimulationActive(!simulationActive)}
          className={`flex items-center space-x-2 px-3 py-1.5 text-[10px] font-mono uppercase tracking-widest rounded-none border transition-all cursor-pointer ${
            simulationActive 
              ? "bg-emerald-600/10 text-emerald-400 border-emerald-500/30" 
              : "bg-zinc-900 text-zinc-500 border-white/10"
          }`}
        >
          <Play className={`h-3 w-3 ${simulationActive ? "animate-spin" : ""}`} />
          <span>SIMULATION: {simulationActive ? "RUNNING_LIVE" : "PAUSED"}</span>
        </button>
      </div>

      {/* Match Day Phase selector */}
      <div className="bg-black border border-white/10 p-4 mb-6">
        <span className="block text-[9px] text-zinc-500 font-mono font-black uppercase tracking-widest mb-3">
          SELECT MATCHDAY CHRONOLOGY (DETERMINES TELEMETRY INGRESS/EGRESS SPEED)
        </span>
        <div className="grid grid-cols-3 gap-2">
          {[
            { phase: "ingress", label: "Pre-Match Ingress", desc: "Heavy Entry Scan" },
            { phase: "halftime", label: "Halftime Interval", desc: "Heavy Concourse Load" },
            { phase: "egress", label: "Post-Match Egress", desc: "Critical Outflow Load" }
          ].map((item) => (
            <button
              key={item.phase}
              onClick={() => setMatchPhase(item.phase as any)}
              className={`p-3 text-left rounded-none border transition-all cursor-pointer flex flex-col justify-between h-18 ${
                matchPhase === item.phase
                  ? "bg-white text-black border-white"
                  : "bg-zinc-950 text-zinc-400 border-white/5 hover:border-white/10"
              }`}
            >
              <span className="text-xs font-black uppercase tracking-tight">{item.label}</span>
              <span className={`text-[8px] font-mono uppercase tracking-tight ${matchPhase === item.phase ? "text-zinc-700 font-bold" : "text-zinc-600"}`}>
                {item.desc}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Main Grid: Telemetry Scans (Left) and AI Forecast (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* SENSOR INPUTS TELEMETRY (5/12 cols) */}
        <div className="lg:col-span-5 bg-zinc-900 border border-white/5 p-5 space-y-4">
          
          <div className="flex items-center space-x-1.5 text-blue-400 font-mono text-[9px] uppercase tracking-widest font-black pb-2 border-b border-white/10">
            <Server className="h-3.5 w-3.5" />
            <span>IOT_METRIC_ACQUISITION</span>
          </div>

          {/* CCTV */}
          <div className="flex items-center justify-between p-3 bg-black border border-white/5">
            <div className="flex items-center space-x-3">
              <Eye className="h-4 w-4 text-sky-400" />
              <div>
                <span className="block text-[9px] text-zinc-500 font-mono uppercase tracking-wider">CCTV VISION NODES</span>
                <span className="text-xs text-white font-bold font-mono">Active Streams: 312</span>
              </div>
            </div>
            <div className="text-right">
              <span className="block text-[10px] font-mono text-zinc-400 uppercase font-black tracking-tight">{sensorData.cctvCount.toLocaleString()}</span>
              <span className="text-[8px] text-sky-400 font-mono uppercase">People counted</span>
            </div>
          </div>

          {/* WIFI */}
          <div className="flex items-center justify-between p-3 bg-black border border-white/5">
            <div className="flex items-center space-x-3">
              <Wifi className="h-4 w-4 text-emerald-400 animate-pulse" />
              <div>
                <span className="block text-[9px] text-zinc-500 font-mono uppercase tracking-wider">WIFI ACCESS HANDSHAKES</span>
                <span className="text-xs text-white font-bold font-mono">Stadium SSID APs: 480</span>
              </div>
            </div>
            <div className="text-right">
              <span className="block text-[10px] font-mono text-zinc-400 uppercase font-black tracking-tight">{sensorData.wifiLogins.toLocaleString()}</span>
              <span className="text-[8px] text-emerald-400 font-mono uppercase">Live connections</span>
            </div>
          </div>

          {/* BLUETOOTH BEACONS */}
          <div className="flex items-center justify-between p-3 bg-black border border-white/5">
            <div className="flex items-center space-x-3">
              <Radio className="h-4 w-4 text-indigo-400" />
              <div>
                <span className="block text-[9px] text-zinc-500 font-mono uppercase tracking-wider">BLUETOOTH BEACONS</span>
                <span className="text-xs text-white font-bold font-mono">Proximity Beacons: 120</span>
              </div>
            </div>
            <div className="text-right">
              <span className="block text-[10px] font-mono text-zinc-400 uppercase font-black tracking-tight">{sensorData.bluetoothPings.toLocaleString()}</span>
              <span className="text-[8px] text-indigo-400 font-mono uppercase">Device handshakes</span>
            </div>
          </div>

          {/* TURNSTILE TICKET SCANS */}
          <div className="flex items-center justify-between p-3 bg-black border border-white/5">
            <div className="flex items-center space-x-3">
              <QrCode className="h-4 w-4 text-yellow-400" />
              <div>
                <span className="block text-[9px] text-zinc-500 font-mono uppercase tracking-wider">TURNSTILE INGRESS FEED</span>
                <span className="text-xs text-white font-bold font-mono">Gates Ingress: Active</span>
              </div>
            </div>
            <div className="text-right">
              <span className="block text-[10px] font-mono text-zinc-400 uppercase font-black tracking-tight">{sensorData.ticketScansMin}/min</span>
              <span className="text-[8px] text-yellow-400 font-mono uppercase">Scan velocity</span>
            </div>
          </div>

          {/* IoT Infrared plates */}
          <div className="flex items-center justify-between p-3 bg-black border border-white/5">
            <div className="flex items-center space-x-3">
              <TrendingUp className="h-4 w-4 text-purple-400" />
              <div>
                <span className="block text-[9px] text-zinc-500 font-mono uppercase tracking-wider">CORRIDOR PRESSURE PLATES</span>
                <span className="text-xs text-white font-bold font-mono">IR Grid Array: Online</span>
              </div>
            </div>
            <div className="text-right">
              <span className="block text-[10px] font-mono text-zinc-400 uppercase font-black tracking-tight">{sensorData.iotFloorPlates}%</span>
              <span className="text-[8px] text-purple-400 font-mono uppercase">Mean area density</span>
            </div>
          </div>

        </div>

        {/* AI FORWARD GRAPH FORECASTS (7/12 cols) */}
        <div className="lg:col-span-7 bg-zinc-900 border border-white/5 p-5 flex flex-col justify-between">
          
          <div>
            <div className="flex items-center justify-between pb-2 border-b border-white/10 mb-4">
              <div className="flex items-center space-x-1.5 text-blue-400 font-mono text-[9px] uppercase tracking-widest font-black">
                <TrendingUp className="h-3.5 w-3.5" />
                <span>AI_COGNITIVE_FORECAST_15_60M</span>
              </div>

              {/* Congestion risk level label */}
              <span className={`text-[10px] font-mono font-black px-2.5 py-0.5 border rounded-none uppercase ${
                bottleneckRisk === "Critical" ? "bg-red-500/20 text-red-400 border-red-500/40 animate-pulse" :
                bottleneckRisk === "High" ? "bg-amber-500/20 text-amber-400 border-amber-500/40" :
                "bg-emerald-500/20 text-emerald-400 border-emerald-500/40"
              }`}>
                BOTTLENECK_RISK: {bottleneckRisk}
              </span>
            </div>

            {/* Simulated Predictive graph using SVG */}
            <div className="bg-black border border-white/5 p-4 rounded-none mb-4">
              <span className="block text-[9px] text-zinc-500 font-mono uppercase font-black tracking-widest mb-3 text-center">
                BOTTLENECK DENSITY FORECAST (1-HOUR OUTLOOK)
              </span>

              <svg viewBox="0 0 320 120" className="w-full h-auto">
                {/* Horizontal grid lines */}
                <line x1="10" y1="20" x2="310" y2="20" className="stroke-white/5 stroke-1" strokeDasharray="2,2" />
                <line x1="10" y1="50" x2="310" y2="50" className="stroke-white/5 stroke-1" strokeDasharray="2,2" />
                <line x1="10" y1="80" x2="310" y2="80" className="stroke-white/5 stroke-1" strokeDasharray="2,2" />
                <line x1="10" y1="100" x2="310" y2="100" className="stroke-white/10 stroke-1" />

                {/* Graph plotted points depending on MatchPhase */}
                {/* Line coordinates */}
                {matchPhase === "ingress" && (
                  <path
                    d="M 10,95 Q 80,60 160,30 T 310,15"
                    className="fill-none stroke-red-500 stroke-2"
                  />
                )}
                {matchPhase === "halftime" && (
                  <path
                    d="M 10,60 Q 80,15 160,50 T 310,85"
                    className="fill-none stroke-amber-400 stroke-2"
                  />
                )}
                {matchPhase === "egress" && (
                  <path
                    d="M 10,98 Q 80,85 150,20 T 310,5"
                    className="fill-none stroke-red-600 stroke-2"
                  />
                )}

                {/* Labels */}
                <text x="12" y="112" className="text-[7px] fill-zinc-500 font-mono">NOW</text>
                <text x="110" y="112" className="text-[7px] fill-zinc-500 font-mono">15M OUT</text>
                <text x="210" y="112" className="text-[7px] fill-zinc-500 font-mono">30M OUT</text>
                <text x="290" y="112" className="text-[7px] fill-zinc-500 font-mono">60M OUT</text>

                {/* Vertical marker lines */}
                <line x1="110" y1="10" x2="110" y2="100" className="stroke-white/5 stroke-1" strokeDasharray="3,3" />
                <line x1="210" y1="10" x2="210" y2="100" className="stroke-white/5 stroke-1" strokeDasharray="3,3" />
              </svg>
            </div>

            {/* Warning Details */}
            <div className="space-y-2">
              <span className="block text-[9px] text-zinc-500 font-mono font-black uppercase tracking-widest">
                PREDICTED CONGESTION SPOTS (IMMEDIATE DEPLOYMENT NEEDED)
              </span>

              <div className="grid grid-cols-1 gap-2">
                {criticalSectors.map((sect, idx) => (
                  <div key={idx} className="bg-black/40 border border-white/5 p-2.5 rounded-none flex items-center space-x-2 text-[11px] font-mono">
                    <AlertTriangle className={`h-3.5 w-3.5 shrink-0 ${bottleneckRisk === "Critical" ? "text-red-500 animate-pulse" : "text-amber-500"}`} />
                    <span className="text-zinc-300 font-bold uppercase">{sect}</span>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Predicted wait times breakdown */}
          <div className="mt-6 border-t border-white/10 pt-4 grid grid-cols-2 md:grid-cols-4 gap-3">
            {Object.entries(predictedGateWaitTimes).map(([gate, mins]) => (
              <div key={gate} className="bg-black p-2.5 border border-white/5 text-center rounded-none">
                <span className="block text-[8px] text-zinc-500 uppercase font-black tracking-widest font-mono">{gate.split(" ")[1] + " " + gate.split(" ")[2]}</span>
                <span className={`text-sm font-black font-mono block mt-1 ${
                  (mins as number) > 30 ? "text-red-500" : (mins as number) > 15 ? "text-amber-500" : "text-emerald-400"
                }`}>
                  {mins} MINS
                </span>
                <span className="text-[8px] text-zinc-600 font-mono uppercase block mt-0.5">Forecasted Q</span>
              </div>
            ))}
          </div>

        </div>

      </div>

    </div>
  );
}
